export const defaultTheme = {
  colors: {
    white: '#FFF',
    background: '#F0F0F5',
    red: '#DE3838 ',
    yellow: '#FFD836',
    orange: '#FFA585',
    gray: '#737380',
    'light-gray': '#E9E9F0',
    'base-logo': '#5D5D6D',
    'base-subtitle': '#403937',
    'base-text-dark': '#41414D',
    'base-text': '#000000CC',
    'base-label': '#8D8686',
    'base-hover': '#D7D5D5',
    'base-button-primary': '#51B853',
    'base-button-secondary': '#115D8C',
    'base-input': '#F3F5F6',
    'base-card': '#FFF',
    'base-card-secondary': '#F1F1F1',
  },
  textSizes: {
    'logo-l': '4rem',
    'title-xl': '4.8rem',
    'title-l': '3.2rem',
    'title-m': '2.4rem',
    'title-s': '2rem',
    'title-xs': '1.8rem',
    'text-l': '2rem',
    'text-m': '1.6rem',
    'text-s': '1.4rem',
    'text-xs': '1rem',
    'text-bold-xs': '1.2rem',
    'tag-bold': '1rem',
    'button-bold-g': '1.4rem',
    'button-regular-m': '1.4rem',
  },
  breakpoints: {
    XS: 0,
    SM: '576px',
    MD: '768px',
    LG: '992px',
    XL: '1200px',
  },
  fonts: {
    default: 'var(--font-saira), sans-serif;',
    logoFont: 'var(--font-stencil-one), sans-serif;',
  },
};
